import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Brand, Button, Card, Heading, Pill, Screen, palette } from '@/components/shop-ui';
import { toneForStatus, useShop } from '@/context/shop-store';
import { useAuth } from '@/context/auth-store';

export default function Dashboard() {
  const router = useRouter(); const { orders, products } = useShop(); const { openProfile } = useAuth();
  const recent = orders.slice(0, 3); const lowStock = products.filter((item) => item.stock < 5).length;
  return <Screen><SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.top}><Brand /><Pressable onPress={openProfile} hitSlop={8} style={styles.avatar}><Text style={styles.avatarText}>AK</Text></Pressable></View><Heading eyebrow="Saturday, 20 September" title="Good morning, Aanya" />
    <Card style={styles.hero}><View style={styles.heroCopy}><Text style={styles.heroEyebrow}>ORDER DESK</Text><Text style={styles.heroTitle}>Turn every message into a clear order.</Text><Text style={styles.heroText}>Paste customer requests, review details, and keep your shop moving.</Text><Button label="Create new order" onPress={() => router.push('/add-order')} /></View></Card>
    <View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Today at a glance</Text><Text style={styles.sectionHint}>Local mock data</Text></View><View style={styles.stats}><Stat value={`${orders.filter(x => x.status !== 'Delivered').length}`} label="Open orders" accent="#137A55" /><Stat value="₹18.4k" label="Order value" accent="#4D82E6" /><Stat value={`${lowStock}`} label="Low in stock" accent="#E08832" /></View>
    <View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Recent orders</Text><Pressable onPress={() => router.push('/orders')} hitSlop={8}><Text style={styles.link}>View all</Text></Pressable></View><Card style={styles.listCard}>{recent.map((order, index) => <View key={order.id} style={[styles.order, index < recent.length - 1 && styles.orderLine]}><View style={styles.orderAvatar}><Text style={styles.orderAvatarText}>{order.name.split(' ').map(x => x[0]).join('')}</Text></View><View style={styles.orderCopy}><Text style={styles.orderName}>{order.name}</Text><Text style={styles.orderDetail}>{order.item}</Text></View><Pill label={order.status} tone={toneForStatus(order.status)} /></View>)}</Card>
    <Pressable onPress={() => router.push('/inventory')} style={styles.alert}><Text style={styles.alertIcon}>!</Text><View><Text style={styles.alertTitle}>{lowStock} inventory items need attention</Text><Text style={styles.alertText}>Review stock levels before confirming new orders.</Text></View></Pressable>
  </ScrollView></SafeAreaView></Screen>;
}
function Stat({ value, label, accent }: { value: string; label: string; accent: string }) { return <Card style={styles.stat}><View style={[styles.statDot, { backgroundColor: accent }]} /><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></Card>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: 20, gap: 22, paddingBottom: 132, maxWidth: 720, width: '100%', alignSelf: 'center' }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, avatar: { width: 37, height: 37, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: '#D9EEE4' }, avatarText: { color: palette.green, fontWeight: '800', fontSize: 12 }, hero: { backgroundColor: '#163F31', borderColor: '#163F31' }, heroCopy: { gap: 12 }, heroEyebrow: { fontSize: 11, color: '#9BD5B9', fontWeight: '800', letterSpacing: 1.1 }, heroTitle: { maxWidth: 280, color: '#FFF', fontSize: 25, lineHeight: 30, fontWeight: '800' }, heroText: { maxWidth: 270, color: '#CBE4D6', fontSize: 13, lineHeight: 19 }, sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { color: palette.ink, fontSize: 17, fontWeight: '800' }, sectionHint: { color: palette.muted, fontSize: 11 }, link: { color: palette.green, fontSize: 13, fontWeight: '800' }, stats: { flexDirection: 'row', gap: 9 }, stat: { flex: 1, padding: 12, gap: 4 }, statDot: { width: 7, height: 7, borderRadius: 4 }, statValue: { color: palette.ink, fontSize: 20, fontWeight: '800' }, statLabel: { color: palette.muted, fontSize: 11, lineHeight: 14 }, listCard: { paddingVertical: 2 }, order: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 13 }, orderLine: { borderBottomWidth: 1, borderBottomColor: '#EEF3F0' }, orderAvatar: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#EAF3EE', alignItems: 'center', justifyContent: 'center' }, orderAvatarText: { color: palette.green, fontSize: 11, fontWeight: '800' }, orderCopy: { flex: 1, gap: 2 }, orderName: { color: palette.ink, fontSize: 14, fontWeight: '700' }, orderDetail: { color: palette.muted, fontSize: 12 }, alert: { flexDirection: 'row', gap: 11, padding: 14, backgroundColor: '#FFF4E8', borderRadius: 15 }, alertIcon: { width: 21, height: 21, textAlign: 'center', borderRadius: 11, overflow: 'hidden', backgroundColor: '#F0A151', color: '#FFF', fontWeight: '900' }, alertTitle: { color: '#93551E', fontSize: 13, fontWeight: '800', marginBottom: 3 }, alertText: { color: '#A86A35', fontSize: 12 } });
