import { ReactNode } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View, ViewStyle } from 'react-native';

export const palette = { ink: '#19362C', muted: '#6D827A', green: '#137A55', pale: '#E7F6EE', canvas: '#F7FAF8', line: '#E4ECE7', orange: '#F49B48', red: '#D9685D', blue: '#4D82E6' };
export function Screen({ children }: { children: ReactNode }) { return <View style={styles.screen}>{children}</View>; }
export function Brand() { return <View style={styles.brand}><View style={styles.brandMark}><Text style={styles.brandMarkText}>w</Text></View><Text style={styles.brandText}>WhatsAppShop</Text></View>; }
export function Heading({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <View style={styles.heading}><View>{eyebrow && <Text style={styles.eyebrow}>{eyebrow}</Text>}<Text style={styles.title}>{title}</Text></View>{action}</View>; }
export function Card({ children, style }: { children: ReactNode; style?: ViewStyle }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Button({ label, onPress, secondary = false }: { label: string; onPress?: () => void; secondary?: boolean }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.buttonSecondary, pressed && { opacity: 0.85 }]}><Text style={[styles.buttonText, secondary && styles.buttonSecondaryText]}>{label}</Text></Pressable>; }
export function Pill({ label, tone = 'green' }: { label: string; tone?: 'green' | 'orange' | 'blue' | 'red' | 'gray' }) { return <View style={[styles.pill, styles[`pill_${tone}`]]}><Text style={[styles.pillText, styles[`pillText_${tone}`]]}>{label}</Text></View>; }
export function Field({ label, placeholder, multiline = false, value, onChangeText }: { label: string; placeholder: string; multiline?: boolean; value?: string; onChangeText?: (text: string) => void }) { return <View style={styles.fieldWrap}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#A3B1AB" multiline={multiline} textAlignVertical={multiline ? 'top' : 'center'} style={[styles.input, multiline && styles.textarea]} /></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: palette.canvas }, brand: { flexDirection: 'row', alignItems: 'center', gap: 9 }, brandMark: { width: 30, height: 30, borderRadius: 10, backgroundColor: palette.green, alignItems: 'center', justifyContent: 'center' }, brandMarkText: { color: '#FFF', fontWeight: '900', fontSize: 20, lineHeight: 22 }, brandText: { color: palette.ink, fontSize: 17, fontWeight: '800', letterSpacing: -0.5 }, heading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, eyebrow: { fontSize: 12, color: palette.green, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.1, marginBottom: 5 }, title: { fontSize: 28, color: palette.ink, fontWeight: '800', letterSpacing: -0.8 }, card: { backgroundColor: '#FFF', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: palette.line }, button: { minHeight: 48, borderRadius: 14, backgroundColor: palette.green, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, buttonText: { color: '#FFF', fontSize: 15, fontWeight: '800' }, buttonSecondary: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#BFD7CA' }, buttonSecondaryText: { color: palette.green }, pill: { alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 20 }, pillText: { fontSize: 11, fontWeight: '800' }, pill_green: { backgroundColor: '#E1F5EA' }, pillText_green: { color: '#137A55' }, pill_orange: { backgroundColor: '#FFF0DF' }, pillText_orange: { color: '#B5681F' }, pill_blue: { backgroundColor: '#E8EFFF' }, pillText_blue: { color: '#426BB6' }, pill_red: { backgroundColor: '#FCE8E5' }, pillText_red: { color: '#B84F46' }, pill_gray: { backgroundColor: '#EEF2EF' }, pillText_gray: { color: '#61736B' }, fieldWrap: { gap: 8 }, fieldLabel: { color: palette.ink, fontSize: 13, fontWeight: '700' }, input: { minHeight: 50, borderWidth: 1, borderColor: '#DCE7E1', backgroundColor: '#FFF', borderRadius: 13, paddingHorizontal: 14, color: palette.ink, fontSize: 15 }, textarea: { height: 128, paddingTop: 14 } });
